### ISSUE TITLE
Ctrl+Enter doesn't work

### ISSUE THREAD

**Issue by thinktwise** [luzhanov/anki-adder-fork#1]
Big blue Ctrl+Enter button works when one clicks on it, but the convenient and clearly stated "Ctrl  Enter" keyboard shortcut doesn't.  
At least in Windows 10 with regularly updated Chrome.

**Comment by luzhanov** [comment]
Fixed & published, new version 1.1.2 will be available in the Chrome Store after few hours.
Thank you for reporting!

**Comment by thinktwise** [comment]
I've been out and didn't see this before. It does work now... Thanks to you
for fixing it!

**Comment by thinktwise** [comment]
Well, actually it doesn't. I don't know how it did this morning, once, but
it doesn't anymore now... Maybe it has something to do with the fact that I
had reinstalled all my computer from cero this morning. Maybe, entering a
word through Anki adder plus, or doins something else in the addin or the
browser stops it from working... ??

**Comment by luzhanov** [comment]
@techmart , could you please check the plugin version in the Chrome's Settings-Extension page?
It should be 1.1.2
I checked it on the latest Chrome version (51.0.2704.106 m) on Windows 8 and it works for me.

**Comment by thinktwise** [comment]
Yes, it is 1.1.2, and same Chrome version as yours, just in Windows 10 pro.
Today I have tried it more extensively and I'm seeing that it is actually
working 3 out of 4 times - so a 25% % of the times it is not..

Can't figure out a commonality among  the times it doesn't though, hope you
are better at that...

Best,

## 

Mart
